# Conclusies

Deelnemers aan deze studie gaven hun voorkeur aan voor trendfiguren.
Daarnaast lieten we hen twee reeksen van drie trendfiguren interpreteren.
De eerste reeks was de meest eenvoudige figuur met de schaal van de y-as als een index.
De tweede reeks was in de voorkeursstijl van de deelnemer.

**Globale voorkeur**

De deelnemers hadden een lichte voorkeur voor een y-as met een index in plaats van een procentuele wijziging.
Het merendeel vond de referentielijnen een meerwaarde.
De annotatie van deze lijnen was eveneens belangrijk.
Driekwart van de deelnemers koos voor de weergave van de onzekerheid, bij voorkeur met een eenvoudig band in plaats van een gradiënt.
De indeling van de trends met behulp van symbolen werd door een derde van de deelnemers gesmaakt.

Deelnemers die aangaven minder vertrouwd te zijn met cijfers en statistiek, kiezen iets vaker voor een meer eenvoudige figuur zonder referentielijnen en onzekerheid en met een index in plaats van procentuele wijziging op de y-as.
Qua voorkeur voor symbolen was er geen verschil tussen de types deelnemers.

**Effect op correcte inschatting**

Beide reeksen figuren die we de deelnemers voorschotelden, hadden dezelfde onderliggende gegevens.
Ze verschilden enkel in de manier van weergave.
Hierdoor kunnen we een eerste inschatting maken van het effect van de weergave op de mogelijkheid om de figuur juist te interpreteren.
Aangezien meer dan 90% van de deelnemers zowel een betrouwbaarheidsinterval wensten als bijkomende referentielijnen, kunnen we deze effecten niet van elkaar onderscheiden.
We hebben ze daarom samen genomen als het effect van de tweede reeks.

Bij de eerste reeks met de eenvoudige figuur gaven slechts vier van de tien deelnemers een correcte interpretatie van de figuur.
We stelden hierbij vooral een overinterpretatie van de trendfiguren vast: de deelnemers hadden de neiging om niet significante effecten toch als een significant te interpreteren.
Bij de tweede reeks was driekwart van de antwoorden correct.
Hou hierbij in het achterhoofd dat de deelnemers bij deze reeks meestal zowel het betrouwbaarheidsinterval als de referentielijnen te zien kregen.
Tijdens de tweede reeks was er veel minder overinterpretatie van de figuren.
De meest voorkomende verkeerde interpretaties waren onduidelijk in plaats van vergelijkbaar en omgekeerd.

**Aanbevelingen voor verder onderzoek**

Het is wenselijk om in de toekomst meer deelnemers aan te trekken die zich minder vertrouwd voelen met cijfers en of statistiek.
Gezien het onderwerp zal dat geen eenvoudige klus zijn.
Om het effect van betrouwbaarheidsintervallen en referentielijnen van elkaar te kunnen onderscheiden, moeten we een aangepaste vragenlijst opstellen.
