---
title: Op zoek naar een optimale trendfiguur
author:
  - name:
      given: Thierry
      family: Onkelinx
    email: thierry.onkelinx@inbo.be
    orcid: 0000-0001-8804-4216
    affiliation: Research Institute for Nature and Forest (INBO)
    corresponding: true
reviewer:
  - name:
      given: Raïsa
      family: Carmen
    email: raisa.carmen@inbo.be
    orcid: 0000-0003-1025-8702
    affiliation: Research Institute for Nature and Forest (INBO)
lang: nl
style: INBO
floatbarrier: subsubsection
keywords: "trend; onzekerheid"
community: "inbo"
publication_type: report
funder: Research Institute for Nature and Forest (INBO)
rightsholder: Research Institute for Nature and Forest (INBO)
bibliography: references.bib
link-citations: TRUE
site: bookdown::bookdown_site
nocolophon: TRUE
output:
  INBOmd::gitbook: default
  INBOmd::pdf_report: default
  INBOmd::epub_book: default
# Don't run the format below.
# Only required for RStudio to recognise the project as a bookdown project.
# Hence don't use 'Build all formats'.
  bookdown::dontrun: default
---

# Samenvatting {.unnumbered}

<!-- description: start -->

De tekst voor de verplichte samenvatting.
Hou het [Heerlijk Helder](https://overheid.vlaanderen.be/communicatie/heerlijk-helder).
<!-- description: end -->

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE, eval = TRUE, cache = FALSE, warning = TRUE, error = FALSE,
  message = TRUE, fig.width = 6
)
library(cluster)
library(effectclass)
library(figquest)
library(git2rdata)
library(gridExtra)
library(INBOtheme)
library(INLA)
library(kableExtra)
library(scales)
library(tidyverse)
if (interactive()) {
  theme_set(
    theme_inbo(base_size = 10) +
          theme(axis.title = element_blank())
  )
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72)
      theme_set(
        theme_inbo(base_size = 12) +
          theme(axis.title = element_blank())
      )
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(
        theme_inbo(base_size = 9) +
          theme(axis.title = element_blank())
      )
      update_geom_defaults("point", list(size = 1.5))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(
        theme_inbo(base_size = 12) +
          theme(axis.title = element_blank())
      )
    }
  )
}
conflicted::conflicts_prefer(dplyr::filter, dplyr::lag)
delta_percent <- function(x) {
  label_percent()(x - 1)
}
n_sample <- 1e3
```

```{r read-data}
read_vc("background", "../../data") |>
  transmute(
    .data$id,
    type = ifelse(
      .data$statistics %in% c("familiar", "very familiar"), 3,
      ifelse(
        .data$numbers %in% c("familiar", "very familiar"), 2, 1
      )
    ) |>
      factor(
        levels = 1:3, labels = c("weinig vertrouwd", "enkel cijfers", "beide")
      ),
    cijfers = factor(
      .data$numbers,
      labels = c(
        "niet vertrouwd", "weinig vertrouwd", "vertrouwd", "zeer vertrouwd"
      )
    ),
    statistiek = factor(
      .data$statistics,
      labels = c(
        "niet vertrouwd", "weinig vertrouwd", "vertrouwd", "zeer vertrouwd"
      )
    )
  ) -> background
read_vc("reference", "../../data") |>
  transmute(
    .data$id,
    index = factor(
      .data$index, levels = c("index", "change"),
      labels = c("index", "procentuele wijziging")
    ),
    trend = factor(
      .data$trend, levels = c("strong", "moderate"),
      labels = c("sterk", "matig")
    ),
    referentie = factor(
      .data$reference, levels = c("none", "line", "line + text"),
      labels = c("geen", "lijn", "lijn + tekst")
    )
  ) -> reference
read_vc("uncertainty", "../../data") |>
  transmute(
    .data$id,
    trend = factor(
      .data$trend,
      levels = c(
        "strong trend with high precision",
        "moderate trend with high precision",
        "moderate trend with low precision"
      ),
      labels = c(
        "sterke trend met hoge precisie", "matige trend met hoge precisie",
        "matige trend met lage precisie"
      )
    ),
    onzekerheid = factor(
      .data$uncertainty, levels = c("gradient", "band", "none"),
      labels = c("gradient", "band", "geen")
    )
  ) -> uncertainty
read_vc("classification", "../../data") |>
  transmute(
    .data$id,
    indeling = factor(
      .data$classification, levels = c("colour", "symbol", "none"),
      labels = c("kleursymbool", "symbool", "geen")
    )
  ) -> classification
read_vc("interpretation", "../../data") |>
  transmute(
    .data$id, achteraf = .data$after, eigen = .data$participant,
    score = factor(
      .data$score,
      levels = c("lower", "comparable", "higher", "unclear", "no idea"),
      labels = c("lager", "vergelijkbaar", "hoger", "onduidelijk", "geen idee")
    ),
    waarheid = factor(
      .data$truth,
      levels = c("potential increase", "moderate increase", "stable"),
      labels = c("mogelijke toename", "matige toename", "stabiel")
    )
  ) -> interpretation
```
